- kind: Message
  name: UserSession
  fields:
    - name: sessionId
      type: string
      index: 1
    - name: userId
      type: string
      index: 2
    - name: accountId
      type: string
      index: 3
    - name: version
      type: number
      index: 4
    - name: capabilities
      type: Capabilities
      import: "@phading/user_session_service_interface/capabilities"
      index: 5
    - name: createdTimeMs
      type: number
      index: 6
    - name: renewedTimeMs
      type: number
      index: 7
- kind: SpannerDatabase
  name: UserSessionDatabase
  tables:
    - kind: MessageTable
      name: UserSession
      storedInColumn: data
      columns:
        - sessionId
        - accountId
        - renewedTimeMs
      primaryKeys:
        - sessionId
      indexes:
        - name: ByRenewedTimeMs
          columns:
            - renewedTimeMs
        - name: ByAccountId
          columns:
            - accountId
      insertStatementName: InsertUserSession
      getStatementName: GetUserSession
      updateStatementName: UpdateUserSession
  deletes:
    - name: DeleteUserSession
      table: UserSession
      where:
        op: =
        leftColumn: sessionId
    - name: DeleteExpiredSession
      table: UserSession
      where:
        op: <
        leftColumn: renewedTimeMs
  selects:
    - name: ListSessionsByAccountId
      table: UserSession
      where:
        op: =
        leftColumn: accountId
      getColumns:
        - data
  outputDdl: ./db/ddl
  outputSql: ./db/sql
