- message:
    name: UserSessionData
    fields:
      - name: userId
        type: string
        index: 1
      - name: accountId
        type: string
        index: 2
      - name: canPublishShows
        type: boolean
        index: 3
      - name: canConsumeShows
        type: boolean
        index: 4
- spannerDatabase:
    name: UserSessionDatabase
    tables:
      - name: UserSession
        columns:
          - name: sessionId
            type: string
          - name: data
            type: UserSessionData
          - name: createdTimestamp
            type: timestamp
          - name: renewedTimestamp
            type: timestamp
        primaryKeys:
          - sessionId
        indexes:
          - name: ByRenewedTimestamp
            columns:
              - renewedTimestamp
    inserts:
      - name: InsertSession
        table: UserSession
        setColumns:
          - sessionId
          - data
          - createdTimestamp
          - renewedTimestamp
    deletes:
      - name: DeleteSession
        table: UserSession
        where:
          op: =
          leftColumn: sessionId
      - name: DeleteExpiredSession
        table: UserSession
        where:
          op: <
          leftColumn: renewedTimestamp
    updates:
      - name: UpdateRenewedTimestamp
        table: UserSession
        where:
          op: =
          leftColumn: sessionId
        setColumns:
          - renewedTimestamp
    selects:
      - name: GetSession
        table: UserSession
        where:
          op: =
          leftColumn: sessionId
        getColumns:
          - data
          - renewedTimestamp
    outputDdl: ./db/ddl
    outputSql: ./db/sql
