- kind: SpannerDatabase
  name: UserSessionDatabase
  tables:
    - kind: Table
      name: UserSession
      columns:
        - name: sessionId
          type: string
        - name: userId
          type: string
          nullable: true
        - name: accountId
          type: string
          nullable: true
        - name: createdTimeMs
          type: float64
          nullable: true
        - name: renewedTimeMs
          type: float64
          nullable: true
      primaryKeys:
        - sessionId
      indexes:
        - name: ByRenewedTimeMs
          columns:
            - renewedTimeMs
        - name: ByAccountId
          columns:
            - accountId
        - name: ByUserId
          columns:
            - userId
      insert: InsertUserSession
      delete: DeleteUserSession
      get: GetUserSession
  deletes:
    - name: DeleteExpiredSessions
      table: UserSession
      where:
        op: <
        lColumn: renewedTimeMs
  updates:
    - name: UpdateUserSessionRenewedTime
      table: UserSession
      where:
        op: =
        lColumn: sessionId
      set:
        - renewedTimeMs
  selects:
    - name: ListSessionsByAccountId
      from: UserSession
      where:
        op: =
        lColumn: accountId
      get:
        - sessionId
    - name: ListExpiredSessions
      from: UserSession
      where:
        op: <
        lColumn: renewedTimeMs
      get:
        - sessionId
  outputDdl: ./db/ddl
  outputSql: ./db/sql
