- spannerDatabase:
    name: UserSessionDatabase
    tables:
      - name: UserSession
        columns:
          - name: sessionId
            type: string
          - name: userId
            type: string
          - name: accountId
            type: string
          - name: createdTimestamp
            type: timestamp
          - name: renewedTimestamp
            type: timestamp
          - name: canPublishShows
            type: bool
          - name: canConsumeShows
            type: bool
        primaryKeys:
          - sessionId
        indexes:
          - name: ByRenewedTimestamp
            columns:
              - renewedTimestamp
    inserts:
      - name: InsertSession
        table: UserSession
        setColumns:
          - sessionId
          - userId
          - accountId
          - createdTimestamp
          - renewedTimestamp
          - canPublishShows
          - canConsumeShows
    deletes:
      - name: DeleteSession
        table: UserSession
        where:
          op: =
          leftColumn: sessionId
      - name: DeleteExpiredSession
        table: UserSession
        where:
          op: <
          leftColumn: renewedTimestamp
    updates:
      - name: UpdateRenewedTimestamp
        table: UserSession
        where:
          op: =
          leftColumn: sessionId
        setColumns:
          - renewedTimestamp
    selects:
      - name: GetSession
        table: UserSession
        where:
          op: =
          leftColumn: sessionId
        getColumns:
          - userId
          - accountId
          - renewedTimestamp
          - canPublishShows
          - canConsumeShows
    outputDdl: ./db/ddl
    outputSql: ./db/sql
